 2020-06-15 01:26:51,216 - INFO- generated new fontManager
 2020-06-15 01:26:51,380 - INFO- scraping scholarships...
 2020-06-15 01:26:51,380 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/1
 2020-06-15 01:28:29,726 - INFO- navigated to URL
 2020-06-15 01:28:29,783 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/2
 2020-06-15 01:28:30,902 - INFO- navigated to URL
 2020-06-15 01:28:30,950 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/3
 2020-06-15 01:28:33,645 - INFO- navigated to URL
 2020-06-15 01:28:33,692 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/4
 2020-06-15 01:28:35,434 - INFO- navigated to URL
 2020-06-15 01:28:35,479 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/5
 2020-06-15 01:28:38,183 - INFO- navigated to URL
 2020-06-15 01:28:38,229 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/6
 2020-06-15 01:28:40,651 - INFO- navigated to URL
 2020-06-15 01:28:40,696 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/7
 2020-06-15 01:28:44,158 - INFO- navigated to URL
 2020-06-15 01:28:44,202 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/8
 2020-06-15 01:28:47,601 - INFO- navigated to URL
 2020-06-15 01:28:47,646 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/9
 2020-06-15 01:28:50,026 - INFO- navigated to URL
 2020-06-15 01:28:50,071 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/10
 2020-06-15 01:28:52,938 - INFO- navigated to URL
 2020-06-15 01:28:52,982 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/11
 2020-06-15 01:28:53,973 - INFO- navigated to URL
 2020-06-15 01:28:54,018 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/12
 2020-06-15 01:28:54,961 - INFO- navigated to URL
 2020-06-15 01:28:55,006 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/13
 2020-06-15 01:28:56,258 - INFO- navigated to URL
 2020-06-15 01:28:56,305 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/14
 2020-06-15 01:28:57,258 - INFO- navigated to URL
 2020-06-15 01:28:57,304 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/15
 2020-06-15 01:28:58,298 - INFO- navigated to URL
 2020-06-15 01:28:58,344 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/16
 2020-06-15 01:28:59,285 - INFO- navigated to URL
 2020-06-15 01:28:59,331 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/17
 2020-06-15 01:29:00,539 - INFO- navigated to URL
 2020-06-15 01:29:00,614 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/18
 2020-06-15 01:29:02,084 - INFO- navigated to URL
 2020-06-15 01:29:02,129 - INFO- Navigate to desired http://opportunitydesk.org/category/fellowships-and-scholarships/page/19
 2020-06-15 01:30:46,815 - ERROR- Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 603, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 383, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 265, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 641, in urlopen
  File "site-packages\urllib3\util\retry.py", line 368, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 603, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 383, in _make_request
  File "http\client.py", line 1321, in getresponse
  File "http\client.py", line 296, in begin
  File "http\client.py", line 265, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "components.py", line 21, in getPageSource
  File "site-packages\requests\api.py", line 75, in get
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 603, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 344, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
  File "site-packages\urllib3\connection.py", line 370, in connect
  File "site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
  File "ssl.py", line 412, in wrap_socket
  File "ssl.py", line 853, in _create
  File "ssl.py", line 1117, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 641, in urlopen
  File "site-packages\urllib3\util\retry.py", line 368, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 603, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 344, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
  File "site-packages\urllib3\connection.py", line 370, in connect
  File "site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
  File "ssl.py", line 412, in wrap_socket
  File "ssl.py", line 853, in _create
  File "ssl.py", line 1117, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opportunitydesk.py", line 17, in <module>
  File "components.py", line 41, in scrapeScholars
  File "components.py", line 23, in getPageSource
  File "site-packages\requests\api.py", line 75, in get
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 668, in send
  File "site-packages\requests\sessions.py", line 668, in <listcomp>
  File "site-packages\requests\sessions.py", line 247, in resolve_redirects
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

